### ISSUE TITLE
Rebuilding cubes fails

### ISSUE THREAD

**Issue by MattBlissett** [gbif/metrics#1]
Rebuilding cubes fails using the current head.

This also needs to be fixed before we reprocess everything.

```
$ sudo ./backfill
…
…
Caused by: java.io.IOException: BulkLoad encountered an unrecoverable problem
        at org.apache.hadoop.hbase.mapreduce.LoadIncrementalHFiles.bulkLoadPhase(LoadIncrementalHFiles.java:449)
        at org.apache.hadoop.hbase.mapreduce.LoadIncrementalHFiles.doBulkLoad(LoadIncrementalHFiles.java:381)
        at com.urbanairship.datacube.backfill.HBaseSnapshotter.runWithCheckedExceptions(HBaseSnapshotter.java:141)
        ... 4 common frames omitted
Caused by: org.apache.hadoop.hbase.client.RetriesExhaustedException: Failed after attempts=35, exceptions:
Wed Nov 28 16:14:14 CET 2018, RpcRetryingCaller{globalStartTime=1543418054919, pause=100, retries=35}, org.apache.hadoop.hbase.client.NeedUnmanagedConnectionException: The connection has to be unmanaged.
Wed Nov 28 16:14:15 CET 2018, RpcRetryingCaller{globalStartTime=1543418054919, pause=100, retries=35}, org.apache.hadoop.hbase.client.NeedUnmanagedConnectionException: The connection has to be unmanaged.
Wed Nov 28 16:14:15 CET 2018, RpcRetryingCaller{globalStartTime=1543418054919, pause=100, retries=35}, org.apache.hadoop.hbase.client.NeedUnmanagedConnectionException: The connection has to be unmanaged.
Wed Nov 28 16:14:16 CET 2018, RpcRetryingCaller{globalStartTime=1543418054919, pause=100, retries=35}, org.apache.hadoop.hbase.client.NeedUnmanagedConnectionException: The connection has to be unmanaged.
Wed Nov 28 16:14:18 CET 2018, RpcRetryingCaller{globalStartTime=1543418054919, pause=100, retries=35}, org.apache.hadoop.hbase.client.NeedUnmanagedConnectionException: The connection has to be unmanaged.
Wed Nov 28 16:14:22 CET 2018, RpcRetryingCaller{globalStartTime=1543418054919, pause=100, retries=35}, org.apache.hadoop.hbase.client.NeedUnmanagedConnectionException: The connection has to be unmanaged.
Wed Nov 28 16:14:32 CET 2018, RpcRetryingCaller{globalStartTime=1543418054919, pause=100, retries=35}, org.apache.hadoop.hbase.client.NeedUnmanagedConnectionException: The connection has to be unmanaged.
Wed Nov 28 16:14:42 CET 2018, RpcRetryingCaller{globalStartTime=1543418054919, pause=100, retries=35}, org.apache.hadoop.hbase.client.NeedUnmanagedConnectionException: The connection has to be unmanaged.
Wed Nov 28 16:14:52 CET 2018, RpcRetryingCaller{globalStartTime=1543418054919, pause=100, retries=35}, org.apache.hadoop.hbase.client.NeedUnmanagedConnectionException: The connection has to be unmanaged.
Wed Nov 28 16:15:02 CET 2018, RpcRetryingCaller{globalStartTime=1543418054919, pause=100, retries=35}, org.apache.hadoop.hbase.client.NeedUnmanagedConnectionException: The connection has to be unmanaged.
Wed Nov 28 16:15:23 CET 2018, RpcRetryingCaller{globalStartTime=1543418054919, pause=100, retries=35}, org.apache.hadoop.hbase.client.NeedUnmanagedConnectionException: The connection has to be unmanaged.
Wed Nov 28 16:15:43 CET 2018, RpcRetryingCaller{globalStartTime=1543418054919, pause=100, retries=35}, org.apache.hadoop.hbase.client.NeedUnmanagedConnectionException: The connection has to be unmanaged.
Wed Nov 28 16:16:03 CET 2018, RpcRetryingCaller{globalStartTime=1543418054919, pause=100, retries=35}, org.apache.hadoop.hbase.client.NeedUnmanagedConnectionException: The connection has to be unmanaged.
Wed Nov 28 16:16:23 CET 2018, RpcRetryingCaller{globalStartTime=1543418054919, pause=100, retries=35}, org.apache.hadoop.hbase.client.NeedUnmanagedConnectionException: The connection has to be unmanaged.
Wed Nov 28 16:16:43 CET 2018, RpcRetryingCaller{globalStartTime=1543418054919, pause=100, retries=35}, org.apache.hadoop.hbase.client.NeedUnmanagedConnectionException: The connection has to be unmanaged.
Wed Nov 28 16:17:03 CET 2018, RpcRetryingCaller{globalStartTime=1543418054919, pause=100, retries=35}, org.apache.hadoop.hbase.client.NeedUnmanagedConnectionException: The connection has to be unmanaged.
Wed Nov 28 16:17:23 CET 2018, RpcRetryingCaller{globalStartTime=1543418054919, pause=100, retries=35}, org.apache.hadoop.hbase.client.NeedUnmanagedConnectionException: The connection has to be unmanaged.
Wed Nov 28 16:17:43 CET 2018, RpcRetryingCaller{globalStartTime=1543418054919, pause=100, retries=35}, org.apache.hadoop.hbase.client.NeedUnmanagedConnectionException: The connection has to be unmanaged.
Wed Nov 28 16:18:03 CET 2018, RpcRetryingCaller{globalStartTime=1543418054919, pause=100, retries=35}, org.apache.hadoop.hbase.client.NeedUnmanagedConnectionException: The connection has to be unmanaged.
Wed Nov 28 16:18:23 CET 2018, RpcRetryingCaller{globalStartTime=1543418054919, pause=100, retries=35}, org.apache.hadoop.hbase.client.NeedUnmanagedConnectionException: The connection has to be unmanaged.
Wed Nov 28 16:18:44 CET 2018, RpcRetryingCaller{globalStartTime=1543418054919, pause=100, retries=35}, org.apache.hadoop.hbase.client.NeedUnmanagedConnectionException: The connection has to be unmanaged.
Wed Nov 28 16:19:04 CET 2018, RpcRetryingCaller{globalStartTime=1543418054919, pause=100, retries=35}, org.apache.hadoop.hbase.client.NeedUnmanagedConnectionException: The connection has to be unmanaged.
Wed Nov 28 16:19:24 CET 2018, RpcRetryingCaller{globalStartTime=1543418054919, pause=100, retries=35}, org.apache.hadoop.hbase.client.NeedUnmanagedConnectionException: The connection has to be unmanaged.
Wed Nov 28 16:19:44 CET 2018, RpcRetryingCaller{globalStartTime=1543418054919, pause=100, retries=35}, org.apache.hadoop.hbase.client.NeedUnmanagedConnectionException: The connection has to be unmanaged.
Wed Nov 28 16:20:04 CET 2018, RpcRetryingCaller{globalStartTime=1543418054919, pause=100, retries=35}, org.apache.hadoop.hbase.client.NeedUnmanagedConnectionException: The connection has to be unmanaged.
Wed Nov 28 16:20:24 CET 2018, RpcRetryingCaller{globalStartTime=1543418054919, pause=100, retries=35}, org.apache.hadoop.hbase.client.NeedUnmanagedConnectionException: The connection has to be unmanaged.
Wed Nov 28 16:20:44 CET 2018, RpcRetryingCaller{globalStartTime=1543418054919, pause=100, retries=35}, org.apache.hadoop.hbase.client.NeedUnmanagedConnectionException: The connection has to be unmanaged.
Wed Nov 28 16:21:04 CET 2018, RpcRetryingCaller{globalStartTime=1543418054919, pause=100, retries=35}, org.apache.hadoop.hbase.client.NeedUnmanagedConnectionException: The connection has to be unmanaged.
Wed Nov 28 16:21:24 CET 2018, RpcRetryingCaller{globalStartTime=1543418054919, pause=100, retries=35}, org.apache.hadoop.hbase.client.NeedUnmanagedConnectionException: The connection has to be unmanaged.
Wed Nov 28 16:21:44 CET 2018, RpcRetryingCaller{globalStartTime=1543418054919, pause=100, retries=35}, org.apache.hadoop.hbase.client.NeedUnmanagedConnectionException: The connection has to be unmanaged.
Wed Nov 28 16:22:04 CET 2018, RpcRetryingCaller{globalStartTime=1543418054919, pause=100, retries=35}, org.apache.hadoop.hbase.client.NeedUnmanagedConnectionException: The connection has to be unmanaged.
Wed Nov 28 16:22:25 CET 2018, RpcRetryingCaller{globalStartTime=1543418054919, pause=100, retries=35}, org.apache.hadoop.hbase.client.NeedUnmanagedConnectionException: The connection has to be unmanaged.
Wed Nov 28 16:22:45 CET 2018, RpcRetryingCaller{globalStartTime=1543418054919, pause=100, retries=35}, org.apache.hadoop.hbase.client.NeedUnmanagedConnectionException: The connection has to be unmanaged.
Wed Nov 28 16:23:05 CET 2018, RpcRetryingCaller{globalStartTime=1543418054919, pause=100, retries=35}, org.apache.hadoop.hbase.client.NeedUnmanagedConnectionException: The connection has to be unmanaged.
Wed Nov 28 16:23:25 CET 2018, RpcRetryingCaller{globalStartTime=1543418054919, pause=100, retries=35}, org.apache.hadoop.hbase.client.NeedUnmanagedConnectionException: The connection has to be unmanaged.

        at org.apache.hadoop.hbase.client.RpcRetryingCaller.callWithRetries(RpcRetryingCaller.java:147)
        at org.apache.hadoop.hbase.mapreduce.LoadIncrementalHFiles.tryAtomicRegionLoad(LoadIncrementalHFiles.java:748)
        at org.apache.hadoop.hbase.mapreduce.LoadIncrementalHFiles$2.call(LoadIncrementalHFiles.java:428)
        at org.apache.hadoop.hbase.mapreduce.LoadIncrementalHFiles$2.call(LoadIncrementalHFiles.java:426)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)
Caused by: org.apache.hadoop.hbase.client.NeedUnmanagedConnectionException: The connection has to be unmanaged.
        at org.apache.hadoop.hbase.client.ConnectionManager$HConnectionImplementation.getTable(ConnectionManager.java:727)
        at org.apache.hadoop.hbase.client.ConnectionManager$HConnectionImplementation.getTable(ConnectionManager.java:711)
        at org.apache.hadoop.hbase.mapreduce.LoadIncrementalHFiles$4.call(LoadIncrementalHFiles.java:704)
        at org.apache.hadoop.hbase.mapreduce.LoadIncrementalHFiles$4.call(LoadIncrementalHFiles.java:691)
        at org.apache.hadoop.hbase.client.RpcRetryingCaller.callWithRetries(RpcRetryingCaller.java:126)
        ... 7 common frames omitted
```

**Comment by timrobertson100** [comment]
This does not appear to be an issue in production. If it does occur again, we should be able to manually load HFiles in an emergency using a command similar to

```
hbase org.apache.hadoop.hbase.mapreduce.LoadIncrementalHFiles -Dhbase.mapreduce.bulkload.max.hfiles.perRegion.perFamily=1000 -Dcreate.table=no /tmp/tim_maps/points/EPSG_4326 dev_map

```

**Comment by MattBlissett** [comment]
With 44c8e2e8107943de4913c24ffac5aeffe5bb49a1 this now works in Dev and UAT.

Use version 0.33 in production, and master in Dev/UAT.
